In [1]:
# kiran in ONN

In [2]:
import pandas as pd

In [4]:
df = pd.read_excel("BhuNirvighna_Land_Acquisition_Dataset.xlsx")

In [6]:
df.head()

,Project_ID,State,District,Project_Type,Land_Required_Hectare,Land_Acquired_Hectare,Affected_Families,Displaced_Families,Sanction_Date,3A_Notification_Date,...,Compensation_Amount_Crore,RR_Amount_Crore,Compensation_Status,R&R_Progress_Percent,Legal_Disputes_Count,Possession_Status,Historical_Delay_Days,Risk_Score_0_100,Delay_Label,Data_Basis
0,BHNV-00001,West Bengal,Hooghly,Irrigation,169.36,107.95,304,50,2019-05-03,2019-08-29,...,207.80,13.46,Partially paid,97.7,4,Pending,736,58,0,Synthetic prototype; fields modeled on public ...
1,BHNV-00002,Madhya Pradesh,Ujjain,Urban Development,60.51,57.81,94,15,2021-04-29,2023-02-26,...,124.42,6.28,Mostly paid,93.8,4,Substantially complete,1745,49,0,Synthetic prototype; fields modeled on public ...
2,BHNV-00003,Odisha,Sambalpur,Urban Development,84.41,33.67,164,26,2018-11-25,2019-12-18,...,214.35,10.61,Pending,100.0,4,Pending,2240,68,1,Synthetic prototype; fields modeled on public ...
3,BHNV-00004,Gujarat,Ahmedabad,Railway,68.02,46.03,129,24,2018-07-05,2019-05-16,...,223.83,11.34,Partially paid,100.0,1,Partial possession,602,57,0,Synthetic prototype; fields modeled on public ...
4,BHNV-00005,West Bengal,Kolkata,Irrigation,29.96,23.30,48,8,2022-03-02,2023-01-22,...,53.02,5.04,Partially paid,86.7,1,Partial possession,1438,56,0,Synthetic prototype; fields modeled on public ...

In [7]:
df.shape

(2000, 24)

In [8]:
df.to_csv("BhuNirvighna_Land_Acquisition_Dataset.csv", index=False)

In [9]:
check = pd.read_csv("BhuNirvighna_Land_Acquisition_Dataset.csv")
check.head()

,Project_ID,State,District,Project_Type,Land_Required_Hectare,Land_Acquired_Hectare,Affected_Families,Displaced_Families,Sanction_Date,3A_Notification_Date,...,Compensation_Amount_Crore,RR_Amount_Crore,Compensation_Status,R&R_Progress_Percent,Legal_Disputes_Count,Possession_Status,Historical_Delay_Days,Risk_Score_0_100,Delay_Label,Data_Basis
0,BHNV-00001,West Bengal,Hooghly,Irrigation,169.36,107.95,304,50,2019-05-03,2019-08-29,...,207.80,13.46,Partially paid,97.7,4,Pending,736,58,0,Synthetic prototype; fields modeled on public ...
1,BHNV-00002,Madhya Pradesh,Ujjain,Urban Development,60.51,57.81,94,15,2021-04-29,2023-02-26,...,124.42,6.28,Mostly paid,93.8,4,Substantially complete,1745,49,0,Synthetic prototype; fields modeled on public ...
2,BHNV-00003,Odisha,Sambalpur,Urban Development,84.41,33.67,164,26,2018-11-25,2019-12-18,...,214.35,10.61,Pending,100.0,4,Pending,2240,68,1,Synthetic prototype; fields modeled on public ...
3,BHNV-00004,Gujarat,Ahmedabad,Railway,68.02,46.03,129,24,2018-07-05,2019-05-16,...,223.83,11.34,Partially paid,100.0,1,Partial possession,602,57,0,Synthetic prototype; fields modeled on public ...
4,BHNV-00005,West Bengal,Kolkata,Irrigation,29.96,23.30,48,8,2022-03-02,2023-01-22,...,53.02,5.04,Partially paid,86.7,1,Partial possession,1438,56,0,Synthetic prototype; fields modeled on public ...

In [10]:
df = pd.read_excel(r"C:\Users\YourName\Downloads\BhuNirvighna_Land_Acquisition_Dataset.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\YourName\\Downloads\\BhuNirvighna_Land_Acquisition_Dataset.xlsx'

In [11]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (2.0.0)